package Cimindi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Activity;
  private ConceptPresentation props_Date;
  private ConceptPresentation props_Destination;
  private ConceptPresentation props_Stay;
  private ConceptPresentation props_Time;
  private ConceptPresentation props_Trip;
  private ConceptPresentation props_dest_detail;
  private ConceptPresentation props_end_date;
  private ConceptPresentation props_start_date;
  private ConceptPresentation props_time_range;
  private ConceptPresentation props_trip_detail;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Activity:
        if (props_Activity == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Activity");
          props_Activity = cpb.create();
        }
        return props_Activity;
      case LanguageConceptSwitch.Date:
        if (props_Date == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Date");
          props_Date = cpb.create();
        }
        return props_Date;
      case LanguageConceptSwitch.Destination:
        if (props_Destination == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Destination = cpb.create();
        }
        return props_Destination;
      case LanguageConceptSwitch.Stay:
        if (props_Stay == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Stay");
          props_Stay = cpb.create();
        }
        return props_Stay;
      case LanguageConceptSwitch.Time:
        if (props_Time == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("Time");
          props_Time = cpb.create();
        }
        return props_Time;
      case LanguageConceptSwitch.Trip:
        if (props_Trip == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Trip = cpb.create();
        }
        return props_Trip;
      case LanguageConceptSwitch.dest_detail:
        if (props_dest_detail == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("dest_detail");
          props_dest_detail = cpb.create();
        }
        return props_dest_detail;
      case LanguageConceptSwitch.end_date:
        if (props_end_date == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("end_date");
          props_end_date = cpb.create();
        }
        return props_end_date;
      case LanguageConceptSwitch.start_date:
        if (props_start_date == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("start_date");
          props_start_date = cpb.create();
        }
        return props_start_date;
      case LanguageConceptSwitch.time_range:
        if (props_time_range == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("time_range");
          props_time_range = cpb.create();
        }
        return props_time_range;
      case LanguageConceptSwitch.trip_detail:
        if (props_trip_detail == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("trip_detail");
          props_trip_detail = cpb.create();
        }
        return props_trip_detail;
    }
    return null;
  }
}
