package Cimindi.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Activity = 0;
  public static final int Date = 1;
  public static final int Destination = 2;
  public static final int Stay = 3;
  public static final int Time = 4;
  public static final int Trip = 5;
  public static final int dest_detail = 6;
  public static final int end_date = 7;
  public static final int start_date = 8;
  public static final int time_range = 9;
  public static final int trip_detail = 10;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL);
    builder.put(0x5a354b9e51564aefL, Activity);
    builder.put(0x5a354b9e51564af9L, Date);
    builder.put(0x5a354b9e51564aedL, Destination);
    builder.put(0x5a354b9e51564af1L, Stay);
    builder.put(0x5a354b9e51564b65L, Time);
    builder.put(0x5a354b9e51564aeaL, Trip);
    builder.put(0x5a354b9e51564b46L, dest_detail);
    builder.put(0x5a354b9e51564af8L, end_date);
    builder.put(0x5a354b9e51564af6L, start_date);
    builder.put(0x5a354b9e51564b64L, time_range);
    builder.put(0x5a354b9e51564af4L, trip_detail);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
