package Cimindi.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptActivity = createDescriptorForActivity();
  /*package*/ final ConceptDescriptor myConceptDate = createDescriptorForDate();
  /*package*/ final ConceptDescriptor myConceptDestination = createDescriptorForDestination();
  /*package*/ final ConceptDescriptor myConceptStay = createDescriptorForStay();
  /*package*/ final ConceptDescriptor myConceptTime = createDescriptorForTime();
  /*package*/ final ConceptDescriptor myConceptTrip = createDescriptorForTrip();
  /*package*/ final ConceptDescriptor myConceptdest_detail = createDescriptorFordest_detail();
  /*package*/ final ConceptDescriptor myConceptend_date = createDescriptorForend_date();
  /*package*/ final ConceptDescriptor myConceptstart_date = createDescriptorForstart_date();
  /*package*/ final ConceptDescriptor myConcepttime_range = createDescriptorFortime_range();
  /*package*/ final ConceptDescriptor myConcepttrip_detail = createDescriptorFortrip_detail();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptActivity, myConceptDate, myConceptDestination, myConceptStay, myConceptTime, myConceptTrip, myConceptdest_detail, myConceptend_date, myConceptstart_date, myConcepttime_range, myConcepttrip_detail);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Activity:
        return myConceptActivity;
      case LanguageConceptSwitch.Date:
        return myConceptDate;
      case LanguageConceptSwitch.Destination:
        return myConceptDestination;
      case LanguageConceptSwitch.Stay:
        return myConceptStay;
      case LanguageConceptSwitch.Time:
        return myConceptTime;
      case LanguageConceptSwitch.Trip:
        return myConceptTrip;
      case LanguageConceptSwitch.dest_detail:
        return myConceptdest_detail;
      case LanguageConceptSwitch.end_date:
        return myConceptend_date;
      case LanguageConceptSwitch.start_date:
        return myConceptstart_date;
      case LanguageConceptSwitch.time_range:
        return myConcepttime_range;
      case LanguageConceptSwitch.trip_detail:
        return myConcepttrip_detail;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForActivity() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "Activity", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aefL);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704751");
    b.version(3);
    b.property("activity", 0x5a354b9e51564b63L).type(PrimitiveTypeId.STRING).origin("6500184780520704867").done();
    b.aggregate("time", 0x5a354b9e51564b8cL).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b64L).optional(false).ordered(true).multiple(false).origin("6500184780520704908").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "Date", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704761");
    b.version(3);
    b.property("tahun", 0x5a354b9e51564b04L).type(PrimitiveTypeId.INTEGER).origin("6500184780520704772").done();
    b.property("bulan", 0x5a354b9e51564b05L).type(PrimitiveTypeId.INTEGER).origin("6500184780520704773").done();
    b.property("tanggal", 0x5a354b9e51564b06L).type(PrimitiveTypeId.INTEGER).origin("6500184780520704774").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDestination() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "Destination", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aedL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704749");
    b.version(3);
    b.aggregate("detail", 0x5a354b9e51564b45L).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b46L).optional(false).ordered(true).multiple(true).origin("6500184780520704837").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForStay() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "Stay", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af1L);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704753");
    b.version(3);
    b.property("stay", 0x5a354b9e51564b49L).type(PrimitiveTypeId.STRING).origin("6500184780520704841").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTime() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "Time", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704869");
    b.version(3);
    b.property("jam", 0x5a354b9e51564b66L).type(PrimitiveTypeId.INTEGER).origin("6500184780520704870").done();
    b.property("menit", 0x5a354b9e51564b67L).type(PrimitiveTypeId.INTEGER).origin("6500184780520704871").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTrip() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "Trip", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aeaL);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704746");
    b.version(3);
    b.aggregate("detail", 0x5a354b9e51564becL).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af4L).optional(false).ordered(true).multiple(false).origin("6500184780520705004").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFordest_detail() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "dest_detail", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b46L);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704838");
    b.version(3);
    b.aggregate("stay", 0x5a354b9e51564b47L).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af1L).optional(false).ordered(true).multiple(false).origin("6500184780520704839").done();
    b.aggregate("activity", 0x5a354b9e51564b48L).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aefL).optional(false).ordered(true).multiple(true).origin("6500184780520704840").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForend_date() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "end_date", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af8L);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704760");
    b.version(3);
    b.aggregate("date", 0x5a354b9e51564b1aL).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L).optional(false).ordered(true).multiple(false).origin("6500184780520704794").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForstart_date() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "start_date", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af6L);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704758");
    b.version(3);
    b.aggregate("date", 0x5a354b9e51564b19L).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L).optional(false).ordered(true).multiple(false).origin("6500184780520704793").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFortime_range() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "time_range", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b64L);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704868");
    b.version(3);
    b.aggregate("start", 0x5a354b9e51564b79L).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L).optional(false).ordered(true).multiple(false).origin("6500184780520704889").done();
    b.aggregate("end", 0x5a354b9e51564b7aL).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L).optional(false).ordered(true).multiple(false).origin("6500184780520704890").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorFortrip_detail() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Cimindi", "trip_detail", 0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af4L);
    b.class_(false, false, false);
    b.origin("r:5db8c6dc-1bef-4e07-acd1-b3d6fc3befad(Cimindi.structure)/6500184780520704756");
    b.version(3);
    b.aggregate("destination", 0x5a354b9e51564af5L).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aedL).optional(false).ordered(true).multiple(true).origin("6500184780520704757").done();
    b.aggregate("start", 0x5a354b9e51564b1bL).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af6L).optional(false).ordered(true).multiple(false).origin("6500184780520704795").done();
    b.aggregate("end", 0x5a354b9e51564b1cL).target(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af8L).optional(false).ordered(true).multiple(false).origin("6500184780520704796").done();
    return b.create();
  }
}
