package Cimindi.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import java.time.LocalDate;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import java.time.temporal.ChronoUnit;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SProperty;

public final class Trip__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aeaL, "Cimindi.structure.Trip");

  public static final SMethod<Integer> getDurationInDays_id4bKygdA8Yw = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getDurationInDays").modifiers(0, AccessPrivileges.PUBLIC).concept(CONCEPT).baseMethodId(75367278884458400L).languageId(0x9ae039f662e054eeL, 0x68f6fd5bc2434b37L).build2();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getDurationInDays_id4bKygdA8Yw);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static int getDurationInDays_id4bKygdA8Yw(@NotNull SNode __thisNode__) {
    // ambil node start date dan end date dari child 
    SNode startDateNode = SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(__thisNode__, LINKS.detail$mfP3), LINKS.start$2Iw4), LINKS.date$2I30);
    SNode endDateNode = SLinkOperations.getTarget(SLinkOperations.getTarget(SLinkOperations.getTarget(__thisNode__, LINKS.detail$mfP3), LINKS.end$2IJ5), LINKS.date$2Ita);

    // periksa jika ada salah satu tanggal null, return 0
    if (startDateNode == null || endDateNode == null) {
      return 0;
    }

    // buat objek localdate (java) u/ perhitungan
    LocalDate startDate = LocalDate.of(SPropertyOperations.getInteger(startDateNode, PROPS.tahun$2vsD), SPropertyOperations.getInteger(startDateNode, PROPS.bulan$2vFE), SPropertyOperations.getInteger(startDateNode, PROPS.tanggal$2vUF));
    LocalDate endDate = LocalDate.of(SPropertyOperations.getInteger(endDateNode, PROPS.tahun$2vsD), SPropertyOperations.getInteger(endDateNode, PROPS.bulan$2vFE), SPropertyOperations.getInteger(endDateNode, PROPS.tanggal$2vUF));

    // hitung selisih hari
    long duration = ChronoUnit.DAYS.between(startDate, endDate);

    // tambahkan 1 karena 20 okt sampai 23 adalah 4 hari dan return sbg integer
    return (int) (duration + 1);
  }

  /*package*/ Trip__BehaviorDescriptor() {
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Integer) getDurationInDays_id4bKygdA8Yw(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink detail$mfP3 = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aeaL, 0x5a354b9e51564becL, "detail");
    /*package*/ static final SContainmentLink start$2Iw4 = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af4L, 0x5a354b9e51564b1bL, "start");
    /*package*/ static final SContainmentLink date$2I30 = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af6L, 0x5a354b9e51564b19L, "date");
    /*package*/ static final SContainmentLink end$2IJ5 = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af4L, 0x5a354b9e51564b1cL, "end");
    /*package*/ static final SContainmentLink date$2Ita = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af8L, 0x5a354b9e51564b1aL, "date");
  }

  private static final class PROPS {
    /*package*/ static final SProperty tahun$2vsD = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b04L, "tahun");
    /*package*/ static final SProperty bulan$2vFE = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b05L, "bulan");
    /*package*/ static final SProperty tanggal$2vUF = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b06L, "tanggal");
  }
}
