package aan.sandbox;

/*Generated by MPS */


public class stay_cation {
  public static void main(String[] args) {
    System.out.println("=====TripInfo=====");
    System.out.println("Start: " + "2000" + "-" + "12" + "-" + "11");
    System.out.println("End: " + "2000" + "-" + "12" + "-" + "15");
    System.out.println("==================");
    System.out.println("indah");
    System.out.println("checkin" + " at " + "9" + ":" + "11" + " - " + "9" + ":" + "30");
    System.out.println("swin" + " at " + "10" + ":" + "0" + " - " + "10" + ":" + "15");
  }
}
