package Cimindi.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Activity_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Date_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Destination_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Stay_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Time_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Trip_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new dest_detail_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new end_date_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new start_date_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new time_range_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new trip_detail_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aefL), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aedL), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af1L), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564aeaL), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b46L), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af8L), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af6L), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b64L), MetaIdFactory.conceptId(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af4L)).seal();
}
