package Cimindi.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_time_range_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_time_range_NonTypesystemRule() {
  }
  public void applyRule(final SNode time_range, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    // ambil nod time u/waktu mulai dn selesai
    SNode startTimeNode = SLinkOperations.getTarget(time_range, LINKS.start$6ha8);
    SNode endTimeNode = SLinkOperations.getTarget(time_range, LINKS.end$6mku);

    // lakukan pengecekan hanya jika kedua waktu sudah diisi
    if (startTimeNode != null && endTimeNode != null) {
      // ambil nilai properti integer
      int startH = SPropertyOperations.getInteger(startTimeNode, PROPS.jam$67LZ);
      int startM = SPropertyOperations.getInteger(startTimeNode, PROPS.menit$6810);

      int endH = SPropertyOperations.getInteger(endTimeNode, PROPS.jam$67LZ);
      int endM = SPropertyOperations.getInteger(endTimeNode, PROPS.menit$6810);

      // ubah ke total menit supaya mudah di compare
      int startTotalMenit = (startH * 60) + startM;
      int endTotalMenit = (endH * 60) + endM;

      if (endTotalMenit <= startTotalMenit) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(time_range, "waktu selesai harus setelah waktu mulai", "r:cdf7bab4-7410-48e6-9bd0-e2f83d1ac9b3(Cimindi.typesystem)", "75367278884117046", null, errorTarget);
        }
      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.time_range$wq;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink start$6ha8 = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b64L, 0x5a354b9e51564b79L, "start");
    /*package*/ static final SContainmentLink end$6mku = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b64L, 0x5a354b9e51564b7aL, "end");
  }

  private static final class PROPS {
    /*package*/ static final SProperty jam$67LZ = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L, 0x5a354b9e51564b66L, "jam");
    /*package*/ static final SProperty menit$6810 = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L, 0x5a354b9e51564b67L, "menit");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept time_range$wq = MetaAdapterFactory.getConcept(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b64L, "Cimindi.structure.time_range");
  }
}
