package Cimindi.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractNonTypesystemRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.NonTypesystemRule_Runtime;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.errors.messageTargets.MessageTarget;
import jetbrains.mps.errors.messageTargets.NodeMessageTarget;
import jetbrains.mps.errors.IErrorReporter;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.mps.openapi.language.SConcept;

public class check_trip_detail_NonTypesystemRule extends AbstractNonTypesystemRule_Runtime implements NonTypesystemRule_Runtime {
  public check_trip_detail_NonTypesystemRule() {
  }
  public void applyRule(final SNode trip_detail, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    // ambil nod date u/ tanggal muali ddan selesai
    SNode startDateNode = SLinkOperations.getTarget(SLinkOperations.getTarget(trip_detail, LINKS.start$2Iw4), LINKS.date$2I30);
    SNode endDateNode = SLinkOperations.getTarget(SLinkOperations.getTarget(trip_detail, LINKS.end$2IJ5), LINKS.date$2Ita);

    // lakukan pengacekan hannya jika kedua tanggal sudah diisi/tidak null
    if (startDateNode != null && endDateNode != null) {
      // ambil nilai proprti integer dari masing2 node date
      int startY = SPropertyOperations.getInteger(startDateNode, PROPS.tahun$2vsD);
      int startM = SPropertyOperations.getInteger(startDateNode, PROPS.bulan$2vFE);
      int startD = SPropertyOperations.getInteger(startDateNode, PROPS.tanggal$2vUF);

      int endY = SPropertyOperations.getInteger(endDateNode, PROPS.tahun$2vsD);
      int endM = SPropertyOperations.getInteger(endDateNode, PROPS.bulan$2vFE);
      int endD = SPropertyOperations.getInteger(endDateNode, PROPS.tanggal$2vUF);

      // ubah ke format yymmdd agar mudah dicompare sbg satu angka
      int startValue = (startY * 10000) + (startM * 100) + startD;
      int endValue = (endY * 10000) + (endM * 100) + endD;

      // lempar error messg
      if (endValue <= startValue) {
        {
          final MessageTarget errorTarget = new NodeMessageTarget();
          IErrorReporter _reporter_2309309498 = typeCheckingContext.reportTypeError(trip_detail, "tanggal selesia harus setelah tanggal mulai", "r:cdf7bab4-7410-48e6-9bd0-e2f83d1ac9b3(Cimindi.typesystem)", "75367278883946492", null, errorTarget);
        }

      }
    }
  }
  public SAbstractConcept getApplicableConcept() {
    return CONCEPTS.trip_detail$YW;
  }
  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    return new IsApplicableStatus(argument.getConcept().isSubConceptOf(getApplicableConcept()), null);
  }
  public boolean overrides() {
    return false;
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink start$2Iw4 = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af4L, 0x5a354b9e51564b1bL, "start");
    /*package*/ static final SContainmentLink date$2I30 = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af6L, 0x5a354b9e51564b19L, "date");
    /*package*/ static final SContainmentLink end$2IJ5 = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af4L, 0x5a354b9e51564b1cL, "end");
    /*package*/ static final SContainmentLink date$2Ita = MetaAdapterFactory.getContainmentLink(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af8L, 0x5a354b9e51564b1aL, "date");
  }

  private static final class PROPS {
    /*package*/ static final SProperty tahun$2vsD = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b04L, "tahun");
    /*package*/ static final SProperty bulan$2vFE = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b05L, "bulan");
    /*package*/ static final SProperty tanggal$2vUF = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b06L, "tanggal");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept trip_detail$YW = MetaAdapterFactory.getConcept(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af4L, "Cimindi.structure.trip_detail");
  }
}
