package Cimindi.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Date_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Date_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Date$by, initContext);
    record(new Tahun_PD(this));
    record(new Bulan_PD(this));
    record(new Tanggal_PD(this));
  }

  /*package*/ static final class Tahun_PD extends BasePropertyConstraintsDescriptor {
    public Tahun_PD(ConstraintsDescriptor container) {
      super(PROPS.tahun$2vsD, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:00347dd9-7bd5-42be-b569-476d0448bc65(Cimindi.constraints)", "6049834924239440246"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 2000 && propertyValue <= 2100;
    }
  }
  /*package*/ static final class Bulan_PD extends BasePropertyConstraintsDescriptor {
    public Bulan_PD(ConstraintsDescriptor container) {
      super(PROPS.bulan$2vFE, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:00347dd9-7bd5-42be-b569-476d0448bc65(Cimindi.constraints)", "6049834924239485196"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 1 && propertyValue <= 12;
    }
  }
  /*package*/ static final class Tanggal_PD extends BasePropertyConstraintsDescriptor {
    public Tanggal_PD(ConstraintsDescriptor container) {
      super(PROPS.tanggal$2vUF, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:00347dd9-7bd5-42be-b569-476d0448bc65(Cimindi.constraints)", "6049834924239523533"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 1 && propertyValue <= 31;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Date$by = MetaAdapterFactory.getConcept(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, "Cimindi.structure.Date");
  }

  private static final class PROPS {
    /*package*/ static final SProperty tahun$2vsD = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b04L, "tahun");
    /*package*/ static final SProperty bulan$2vFE = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b05L, "bulan");
    /*package*/ static final SProperty tanggal$2vUF = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564af9L, 0x5a354b9e51564b06L, "tanggal");
  }
}
