package Cimindi.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BasePropertyConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.runtime.CheckingNodeContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;

public class Time_Constraints extends BaseConstraintsDescriptor {
  /*package*/ Time_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.Time$wT, initContext);
    record(new Jam_PD(this));
    record(new Menit_PD(this));
  }

  /*package*/ static final class Jam_PD extends BasePropertyConstraintsDescriptor {
    public Jam_PD(ConstraintsDescriptor container) {
      super(PROPS.jam$67LZ, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:00347dd9-7bd5-42be-b569-476d0448bc65(Cimindi.constraints)", "75367278883996633"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 0 && propertyValue <= 23;
    }
  }
  /*package*/ static final class Menit_PD extends BasePropertyConstraintsDescriptor {
    public Menit_PD(ConstraintsDescriptor container) {
      super(PROPS.menit$6810, container, false, false, true);
    }
    @Override
    public boolean validateValue(SNode node, Object propertyValue, CheckingNodeContext checkingNodeContext) {
      boolean result = staticValidateProperty(node, SPropertyOperations.castInteger(propertyValue));
      if (!(result) && checkingNodeContext != null) {
        checkingNodeContext.setBreakingNode(new SNodePointer("r:00347dd9-7bd5-42be-b569-476d0448bc65(Cimindi.constraints)", "75367278884007074"));
      }
      return result;
    }
    private static boolean staticValidateProperty(SNode node, int propertyValue) {
      return propertyValue >= 0 && propertyValue <= 59;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Time$wT = MetaAdapterFactory.getConcept(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L, "Cimindi.structure.Time");
  }

  private static final class PROPS {
    /*package*/ static final SProperty jam$67LZ = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L, 0x5a354b9e51564b66L, "jam");
    /*package*/ static final SProperty menit$6810 = MetaAdapterFactory.getProperty(0x68f6fd5bc2434b37L, 0x9ae039f662e054eeL, 0x5a354b9e51564b65L, 0x5a354b9e51564b67L, "menit");
  }
}
